### ISSUE TITLE
Préparation

### ISSUE THREAD

**Issue by pascalfares** [pascalfares/smb215-15#1]
Lire ce document et suivre les étapes

https://docs.google.com/presentation/d/14OoU27Pa8mhhLQSTEhMrp3IXMoUzJ9ExuNjk4S1iwjA/present#slide=id.g9a756cbf8_0_101

**Comment by nachkar** [comment]
Mr Pascal j'ai suivi les etapes mais je n'ai pas avoir le cours en utilisant le user name et password de l'ISAE .

**Comment by Peter-eid** [comment]
Done :)

**Comment by Ibrahim-Keyrouz** [comment]
Je suis Ici :D 

Mais il y a un probleme dans le login de Moodle , ce dernier dit que mon username n'existe pas. 

![screenshot from 2015-04-25 19 33 32](https://cloud.githubusercontent.com/assets/4200166/7333723/57e7f148-eb82-11e4-86c0-8fa7ea1d3866.png)

**Comment by pascalfares** [comment]
Verifier aussi majuscule muniscule dans le password.

Pascal Fares
http://www.cofares.net
Le 25 avr. 2015 19:36, "Ibrahim Keyrouz" <notifications@github.com> a
écrit :

**Comment by pascalfares** [comment]
il a du te demander une clé pour le cours. utilise smb215

Pascal Fares
http://www.cofares.net

**Comment by ayaha** [comment]
je suis ici M.Pascal

**Comment by robaseifeddine** [comment]
Mr Pascal j'ai suivi les etapes mais je n'ai pas avoir le cours en utilisant le user name et password de l'ISAE ., malgre que le user name et password est exactly correct 100 %, merci

**Comment by pascalfares** [comment]
apres le login pour entrzr dans le cours une clé sera demandée.

il faut indiqué smb215 pour une auto inscription.

Pascal Fares
http://www.cofares.net
Le 26 avr. 2015 15:55, "rouba seif eddine" <notifications@github.com> a
écrit :

**Comment by bilani** [comment]
done.

**Comment by mohamad-dekmak** [comment]
je suis ici. Done!

**Comment by nachkar** [comment]
Done

**Comment by Hayat5** [comment]
je suis ic.

**Comment by Guitta** [comment]
![done](https://cloud.githubusercontent.com/assets/9698466/7410781/ce49c9fe-ef3a-11e4-96cf-efbdd581d7bd.jpg)

**Comment by majedlb** [comment]
Done ;))

**Comment by ShawkiShehadeh** [comment]
Done

**Comment by mmerhej** [comment]
done

**Comment by michel-el-hajj** [comment]
içi

**Comment by tamaraoueidat** [comment]
Done

**Comment by pascalfares** [comment]
Je considère que tout le monde est prêt
