### ISSUE TITLE
Projet Achat

### ISSUE THREAD

**Issue by Ibrahim-Keyrouz** [pascalfares/smb215-15#13]
**Achat :** 
Un employe obtient une notification permettant de l'informer qu'il y a un besoin d'acheter un produit specifique grace a un diminution du stock. 
	 **Pour cette idee on a besoin :**
		 - Une forme (JSF page) dans l'application qui demarre initialement,s'il faut, affichant les produits qui sont manqués **OU BIEN** Une application mobile qui fait un push notification 
		   et notifie l'employe du produit qui est manqué.
	 **L'environement technique pour cette idee:**
		- Technologie Java EE ou Android SDK
		- Web services Rest pour la notification dans Android
		
S'il y a besoin d'acheter un produit (apres que la notification est affichee) : 
L'employe accede la forme "Demande Produit" et entre les donnees (produits) a acheter 
     **Pour cette idee on a besoin :**
		- Une forme "Demande Produit " qui fait le CRUD pour la demande.
	 **L'environement technique pour cette idee:**
		- Technologie Java EE 
		
Apres la demande et lorsque les produits arrivent :
L'employe sauvegarde les produits , un changement du stock et de la table "demande" aura lieu. 
     **Pour cette idee on a besoin :**
	    - Une forme "Reception" qui fait le CRUD de la reception 
	 **L'environement technique pour cette idee:**
		- Technologie Java EE 

**Pour ce projet Achat les produits seront mis dans une chambre initiale de la branche, de cette chambre les produits seront distribues vers les autres chambres/branches/personnes d'ou**
**un autre projet qui est le cartographie**

**Parlons de la base de donnee concernant ce projet:**
- La **table User**
- La **table Product**
- La notification sera dependante d'un flag dans la **table du stock** et d'une **table produit** 
- La demande sera "CRUDée" d'une **table Order** et elle utilisera une **table fournisseur**
- La Reception d'un fournisseur sera "CRUDée" des **2 tables recep et recep_dtl**

@pascalfares je voudrais commencer par ce projet, et je voudrais quelqu'un(e) avec moi.
@smb21515  N'hesitez pas a corriger ce logique pour un bon commencement.

**Comment by mohamad-dekmak** [comment]
I am IN, and ready for this project in parallel with the SSO Project.

**Comment by antoine-ghosn** [comment]
je voudrais commencer par le projet de SSO

**Comment by bilani** [comment]
Hello @Ibrahim-Keyrouz , i started a Design document for Achat (SMB215 - Achat), we car start for here, and if you like we start to add on it functionalities and everything we can come up with. 
just i need to know where i can Upload it

**Comment by bilani** [comment]
also count me in here with you two @Ibrahim-Keyrouz @mohamad-dekmak @pascalfares

**Comment by pascalfares** [comment]
Commence par créer la BD et les tables dans Mysql



*___*
*Il est toujours préférable de trouver une solution que de produire des
excuses*
*Pascal Fares <http://www.cofares.net>*

Enseignant ISAE - Cnam Liban
Chef du département informatique <http://depinfo.isae.edu.lb> Cnam Liban

**Comment by Ibrahim-Keyrouz** [comment]
Ok @pascalfares

**Comment by Ibrahim-Keyrouz** [comment]
@pascalfares  @mohamad-dekmak  @bilani 
Ce sont les tables pour le projet Achat.
N'hesitez pas a corriger ou a modifier.
NB: Ces tables peuvent etre modifier pour etre compatible avec les autres projets

**SITES**       --Pour les branches
Name                     Null                 Type         
------------------        --------                ------------ 
SITEID                 NOT NULL        VARCHAR2(2)    (PK)
DESCRIPTION		               VARCHAR2(20)	



**CATEGORY** 
Name                       Null                Type         
------------------           --------           ------------ 
CATEGORY         NOT NULL       VARCHAR2(4)   (PK)
DESCRIPTION		              VARCHAR2(20)	


**USERS**
Name                        Null                Type         
------------------            --------            ------------ 
USERID                   NOT NULL      VARCHAR2(4)   (PK)
DESCRIPTION                                VARCHAR2(20)    
EMAIL                                              VARCHAR2(50)  
PSWD_ENCRYPT                           RAW(128 BYTE)    
STATUS                   NOT NULL      VARCHAR2(1)    --Pour dire si ce user est activé ou arreté


**Product**
Name                        Null                   Type         
------------------            --------                ------------ 
BARCODE      	         NOT NULL         VARCHAR2(16)   (PK)  --On suppose qu'un seul barcode par produit
DESCRIPTION        NOT NULL          VARCHAR2(20) 
TVA                          NOT NULL          NUMBER(10,3) 
TVA_TYPE               NOT NULL          VARCHAR2(1)  
STATUS                   NOT NULL          VARCHAR2(1) 
CATEGORY                                         VARCHAR2(4)     (FK)
USERID                                               VARCHAR2(4)     (FK)


**Supplier**
Name                            Null                  Type           
------------                       --------               -------------- 
SUPPLIERID               NOT NULL        VARCHAR2(5)    (PK)
DESCRIPTION            NOT NULL        VARCHAR2(20)
TEL                                                       VARCHAR2(20)   
E_MAIL                                                 VARCHAR2(30)   
STATUS                       NOT NULL       VARCHAR2(1)       
ADDRESS                                            VARCHAR2(100)    
USERID                                                VARCHAR2(4)    (FK)

 
*Supplier_products*                            --On suppose qu'on peut acheter le meme produit de plusieurs supplier
Name                              Null                Type         
-----------------                   --------            ------------ 
PRDID                            NOT NULL    VARCHAR2(8)  (FK) (PK)
SUPPLIERID                  NOT NULL    VARCHAR2(5)  (FK) (PK)
USERID                                                VARCHAR2(4)  (FK) (PK)


**Purchases**                               -- Pour la Demande des produits
Name                                Null                  Type         
-------------------                  --------               ------------ 
DOCID                             NOT NULL        VARCHAR2(14) (PK)
SITEID                             NOT NULL        VARCHAR2(2)  (FK)
TRSDATE                       NOT NULL         DATE         
PRDID                             NOT NULL         VARCHAR2(8)  (FK)
SUPPLIERID                                             VARCHAR2(5)  (FK)
QTY                                NOT NULL         NUMBER(8)    
USERID                          NOT NULL         VARCHAR2(4)  (FK)

**Recept**
Name                                  Null                Type         
----------------                     --------               ------------ 
DOCID                             NOT NULL         VARCHAR2(14) (PK)
SITEID                                                       VARCHAR2(2)  (FK)
TRSDATE                                                  DATE         
RELATED_DOCID                                     VARCHAR2(14)  (FK)
INVOICE_DISCOUNT                                NUMBER(4,2)   

**Recept_dtl**
Name                                    Null                  Type         
----------------                       --------                  ------------ 
DOCID                              NOT NULL          VARCHAR2(14)  (FK)
PRDID                                                          VARCHAR2(8)   (FK)
QTY                                                              NUMBER(11,2)  
PURCHASE_PRICE                                     NUMBER(10,3) 
ITEM_DISCOUNT                                        NUMBER(4,2)  

**STK_PRD**       -- le stockage par produit
Name        		            Null                    Type         
------------ 		                  --------                 ----------- 
SITEID       		          NOT NULL        VARCHAR2(2)  (FK)
PRDID        		          NOT NULL        VARCHAR2(8)  (FK)
QTY          		          NOT NULL         NUMBER(15,2)
QTY_NOTIFICATION       NOT NULL         NUMBER(15,2)

**STK_TRS**      -- chaque transaction faite dans la base de donnee est sauvgardée
Name                                  Null                      Type         
--------------                           --------                    ------------ 
SITEID                               NOT NULL             VARCHAR2(2)  
DOCID                               NOT NULL             VARCHAR2(14) 
TRSDATE                          NOT NULL             DATE         
DOCTYPE                         NOT NULL             VARCHAR2(1)  
PRDID                               NOT NULL             VARCHAR2(8)  
QTY                                   NOT NULL             NUMBER(11,2) 
RELATED_DOCID                                          VARCHAR2(14) 
TVA                                                                 NUMBER(10,3) 
TVA_TYPE                                                      VARCHAR2(1)  
SUPPLIERID                                                   VARCHAR2(5)  
USERID                              NOT NULL           VARCHAR2(4)  
PURCHASE_PRICE                                       NUMBER(10,3)

**Comment by Ibrahim-Keyrouz** [comment]
@pascalfares  @mohamad-dekmak  @bilani 
Ce sont les tables pour le projet Achat.
N'hesitez pas a corriger ou a modifier.
NB: Ces tables peuvent etre modifier pour etre compatible avec les autres projets

**SITES**       --Pour les branches
Name ------------  Null--------Type         
------------------ -------- ------------ 
SITEID-----------NOT NULL-----VARCHAR2(2)    (PK)
DESCRIPTION-------------------VARCHAR2(20)	



**CATEGORY** 
Name-----------------Null-------Type         
------------------ -------- ------------ 
CATEGORY------------NOT NULL---VARCHAR2(4)   (PK)
DESCRIPTION--------------------VARCHAR2(20)	


**USERS**
Name-----------------Null--------Type         
------------------ -------- ------------ 
USERID--------------NOT NULL---VARCHAR2(4)   (PK)
DESCRIPTION--------------------VARCHAR2(20)    
EMAIL--------------------------VARCHAR2(50)  
PSWD_ENCRYPT-------------------RAW(128 BYTE)    
STATUS--------------NOT NULL---VARCHAR2(1)    --Pour dire si ce user est activé ou arreté


**Product**
Name------------------Null------Type         
------------------ -------- ------------ 
BARCODE-------------NOT NULL----VARCHAR2(16)   (PK)  --On suppose qu'un seul barcode par produit
DESCRIPTION---------NOT NULL----VARCHAR2(20) 
TVA-----------------NOT NULL----NUMBER(10,3) 
TVA_TYPE------------NOT NULL----VARCHAR2(1)  
STATUS--------------NOT NULL----VARCHAR2(1) 
CATEGORY------------------------VARCHAR2(4)     (FK)
USERID--------------------------VARCHAR2(4)     (FK)


**Supplier**
Name-----------Null-------Type           
------------ -------- -------------- 
SUPPLIERID----NOT NULL---VARCHAR2(5)    (PK)
DESCRIPTION---NOT NULL---VARCHAR2(20)
TEL----------------------VARCHAR2(20)   
E_MAIL-------------------VARCHAR2(30)   
STATUS--------NOT NULL---VARCHAR2(1)       
ADDRESS------------------VARCHAR2(100)    
USERID-------------------VARCHAR2(4)    (FK)

 
*Supplier_products*                            --On suppose qu'on peut acheter le meme produit de plusieurs supplier
Name----------------Null------Type         
----------------- -------- ------------ 
PRDID-------------NOT NULL---VARCHAR2(8)  (FK) (PK)
SUPPLIERID--------NOT NULL---VARCHAR2(5)  (FK) (PK)
USERID-----------------------VARCHAR2(4)  (FK) (PK)


**Purchases**                               -- Pour la Demande des produits
Name------------------Null-------Type         
------------------- -------- ------------ 
DOCID---------------NOT NULL----VARCHAR2(14) (PK)
SITEID--------------NOT NULL----VARCHAR2(2)  (FK)
TRSDATE-------------NOT NULL----DATE         
PRDID---------------NOT NULL----VARCHAR2(8)  (FK)
SUPPLIERID----------------------VARCHAR2(5)  (FK)
QTY-----------------NOT NULL----NUMBER(8)    
USERID--------------NOT NULL----VARCHAR2(4)  (FK)

**Recept**
Name---------------Null-------Type         
---------------- -------- ------------ 
DOCID------------NOT NULL---VARCHAR2(14) (PK)
SITEID----------------------VARCHAR2(2)  (FK)
TRSDATE---------------------DATE         
RELATED_DOCID---------------VARCHAR2(14)  (FK)
INVOICE_DISCOUNT------------NUMBER(4,2)   

**Recept_dtl**
Name---------------Null------Type         
---------------- -------- ------------ 
DOCID------------NOT NULL----VARCHAR2(14)  (FK)
PRDID------------------------VARCHAR2(8)   (FK)
QTY--------------------------NUMBER(11,2)  
PURCHASE_PRICE---------------NUMBER(10,3) 
ITEM_DISCOUNT----------------NUMBER(4,2)  

**STK_PRD**       -- le stockage par produit
Name------------------Null-------Type         
------------ 		-------- ------------ 
SITEID--------------NOT NULL----VARCHAR2(2)  (FK)
PRDID---------------NOT NULL----VARCHAR2(8)  (FK)
QTY-----------------NOT NULL----NUMBER(15,2)
QTY_NOTIFICATION----NOT NULL----NUMBER(15,2)

**STK_TRS**      -- chaque transaction faite dans la base de donnee est sauvgardée
Name-------------Null------Type         
-------------- -------- ------------ 
SITEID---------NOT NULL-----VARCHAR2(2)  
DOCID----------NOT NULL-----VARCHAR2(14) 
TRSDATE--------NOT NULL-----DATE         
DOCTYPE--------NOT NULL-----VARCHAR2(1)  
PRDID----------NOT NULL-----VARCHAR2(8)  
QTY------------NOT NULL-----NUMBER(11,2) 
RELATED_DOCID---------------VARCHAR2(14) 
TVA-------------------------NUMBER(10,3) 
TVA_TYPE--------------------VARCHAR2(1)  
SUPPLIERID -----------------VARCHAR2(5)  
USERID---------NOT NULL-----VARCHAR2(4)  
PURCHASE_PRICE--------------NUMBER(10,3)

**Comment by pascalfares** [comment]
Il faut créer un script sql et le mettre dans le git

*___*
*Il est toujours préférable de trouver une solution que de produire des
excuses*
*Pascal Fares <http://www.cofares.net>*

Enseignant ISAE - Cnam Liban
Chef du département informatique <http://depinfo.isae.edu.lb> Cnam Liban


2015-06-03 16:39 GMT+03:00 Ibrahim Keyrouz <notifications@github.com>:

**Comment by Ibrahim-Keyrouz** [comment]
Hello SMB215 , 
Mon projet est localisé : https://github.com/pascalfares/smb215-15/tree/master/Achat

**Comment by Ibrahim-Keyrouz** [comment]
Hello @smb21515  et @pascalfares  
La nouvelle localisation de mon projet : https://github.com/Ibrahim-Keyrouz/SMB215
