### ISSUE TITLE
Projet SSO

### ISSUE THREAD

**Issue by mohamad-dekmak** [pascalfares/smb215-15#14]
## Def:
On utilise ce projet pour:
* Lier les modules de projet.
* Gerer les utilisateurs et leurs roles.
* Authentifier les utilisateurs  par oAuth (third party provider) pour faciliter les management des utilisateurs.

## Specs:
Sera ajouter plus tard...
## Members
Pour ceux qui souhaitent se joindre...

@smb21515 Please corriger / commenter cette issue pour un bon relation.

**Comment by Ibrahim-Keyrouz** [comment]
@mohamad-dekmak  I'm IN in paralel of the Project Achat

**Comment by bilani** [comment]
@mohamad-dekmak  I'm in also, this weekend i will do a design document of SSO and OAuth

**Comment by antoine-ghosn** [comment]
je voudrais participer dans ce projet .

**Comment by antoine-ghosn** [comment]
Processus d'identification A travers Facebook 

1.	Télécharger la librairie  scribe-1.3.1.jar (OAuth librairie)

2.	Créer votre propre application sur Facebook.
Facebook génère un apiKey et apiSecret pour votre application.

3.	Demander à l'utilisateur de s'inscrire via son compte Facebook pour obtenir un code d'accès (access token) permattant d'obtenir des informations d'un compte Facebook :

Réorienter une demande sur le URL suivant : https://www.facebook.com/dialog/oauth?client_id="+facebookAppID+"&redirect_uri="+this.callbackView
Paramètre: 
o	Le paramètre Client_id doit représente la clé API de notre application sur facebook .
o	 Le paramètre redirect_uri doit contenir (encodé naturellement pour être utilisable dans une url) la page vers laquelle Facebook redirigera l'utilisateur qui a accepté de vous donner des droits.

4.	Facebook redirigera l’utilisateur vers La redirect_uri déjà spécifié :

Lire les paramètres saisir par facebook : (error, error_code, error_description, error_reason et le code)
Ce qui nous intéresse c’est le paramètre Code si l’authentification est validée par facebook.
 	
5.	Obtenir  le code d'accès de l’utilisateur chez Facebook

Créer un OAuthRequest du type Get vers l’URL suivante :
 https://graph.facebook.com/oauth/access_token
Avec les suivantes paramètres:
o	client_id : la clé API de notre application sur facebook.
o	client_secret : la clé secrète de notre application sur facebook.
o	redirect_uri : L’Url que Facebook va se rédigera sa réponse.
o	Code : Le code retourné  du serveur Facebook.
Vous trouverez le code d’accès  dans la reponse.

6.	 Obtenir L’ ID de l’utilisateur chez Facebook

Créer un OAuthRequest du type Get vers l’URL suivante :
 https://graph.facebook.com/debug_token
Avec les suivantes paramètres:
o	input_token: le code d’accès de l’utilisateur.
o	 access_token: represente la clé API concatene avec la clé secrète du notre application avec un ‘|’. (facebookAppID + "|" + facebookAppSecret)

Vous trouverez le « user_id »  dans votre réponse.

**Comment by mohamad-dekmak** [comment]
@antoine-ghosn: 
Please try to start working on this module (facebook API).
I will start on Google API OAuth module.
We will merge the changes when finished in one project.
In parallel, anyone can start working on Twitter module or similar.

**Comment by bilani** [comment]
@mohamad-dekmak  i will start on twitter

**Comment by pascalfares** [comment]
Il ne faut pas mettre dans les issues les specs ou la doc MAIS

les mettre dans des dicumments et faire commit

dans le message du commit vous pouvez

**Comment by mohamad-dekmak** [comment]
OK, noted.

**Comment by mohamad-dekmak** [comment]
@pascalfares,
Please link my project (listed below) to SSO repo, i don't have access to push my project to smb215-15/sso

https://github.com/mohamad-dekmak/OAuth-Google

**Comment by bilani** [comment]
@pascalfares  please link mine as well
https://github.com/bilani/OAuth-Twitter.git
