### ISSUE TITLE
des .class dans le git 

### ISSUE THREAD

**Issue by pascalfares** [pascalfares/smb215-15#17]
Il ne faut pas commiter des .class ou des fichier binaire qui sont génére par compilation

Le git en générale c'est pour les sources....

@smb21515 

Je préfère pour evoter les ptoblème que vous créer vos propre git dans github et me donner le lien vers les projets.... 

ce ser des modules de ce projet SMB215-15

**Comment by mohamad-dekmak** [comment]
Thanks for the tip.
Also, we shouldn't commit the below files:

*.class
*.jar
*.war
*.ear
nbproject/private/
build/
dist/
