### ISSUE TITLE
Trouvons une idée

### ISSUE THREAD

**Issue by pascalfares** [pascalfares/smb215-15#2]
proposer des idée pour le produit en developpement Open Source dans le cadre du cours SMB215 pour l'année 2014-20s15

**Comment by pascalfares** [comment]
En voici une http://libresoftware.cofares.net/projets-par-l-open-source-lebanese-movement/gstockr

**Comment by Ibrahim-Keyrouz** [comment]
Idee 2 : 
Website , Application locale et Android app pour Mega-Shopping (Music albums, PS games ... ) 

Objectif:
Réaliser une application Libre Open Source software pour permettre aux clients d'acheter les produits d'un MegaStore. 
Ce projet va etre deployer sur Github.

Description succincte:
Un Megastore possedant des produits(Music Albums, Microphones,Tickets..) divisés sur des categories(Music,Tecks,..) veut un website pour repondre aux besoins des clients. 
les produits sont entre  consommables et amortissables.
Chaque fois qu'un client achete un produit le stock de ce Megastore est réglé .
Ce MegaStore a besoin encore d'une application locale pour le store .

Ce que l'on souhaiterait réaliser : 
Développer une application permettant de gerer l'achat et le stock dans le magazin. 
Développer une application web permettant aux clients d'acheter online.
Développer une application android seulement pour voire les produits.

**Comment by bilani** [comment]
idee 3:
web based ERP system et android mobile app pour n'importe quelle business.

objectif:
développer un système ERP pour tout type d'entreprise.

Description succincte:
1-l'idée de ce système ERP est de permettre à l'utilisateur de créer un article , un fournisseur et un client
2-perfom une facture de vente , facture d'achat , transfare entre les branches
3-mettre à jour le stock et effectuer des inventaires
4-rendre l'ordonnance sur l'application mobile
5-encas quand un article ne se trouve pas en stock , utilisez  "Android push notification" pour notifier le client quand cet article sera disponible en stock
6-Enu utulisant le GPS, on peut suivi les livraisons , soit entre les branches ou les livraison pour les clients

Ce que l'on souhaiterait réaliser : 
Développer une application backOffice permettant aux utilisateurs de performer les affaire administratifs
Développer une application web permettant aux clients d'acheter online.
Développer une application android pour voire les produits, faire and ordre and etre notify pour des nouveax items ou des items réservé.

**Comment by bilani** [comment]
idee 4:

est-il applicable de faire une application mobile pour les auditeurs du CNAM qui envoie des notification quant les notes sont en line, ou les coures , prof absent ... ?

**Comment by pascalfares** [comment]
Pour l'instant la meilleur idée est la gestion du patrimoine et de l'achat (assets and procurement)

C'est une partie importante de tout l'ERP (sans la partie comptabilité / et CRM)

@Ibrahim-Keyrouz @bilani @Ayah @mohamad-dekmak @nachkar @Guitta

**Comment by mohamad-dekmak** [comment]
I suggest to implement and build a maintenance application, with the following details:

Applications / Specifications | Web Application | Website | Mobile App
----------------------------------- | -------------------- | ---------- | --------------
App Target | Maintenance Enterprises | Clients of maintenance enterprises | Technicians
App Objective | Track the data in one single place. Provide a self-service system available anytime & anywhere. Enhance collaboration. Increase the team productivity | Take the client to add new ticket (order, maintenance, request an enhancement, feedback, information, ...) | provide an extra layer of flexibility by allowing technicians to enter any and all information about preventative maintenance, work orders, minimizing errors and saving time and effort.
App Installation Environment | on-server or on-cloud | on-cloud | smartphone and tablet 
App Features | Maintenance Job Calendar, Dashboard, Reports, Notifications, Reminders, Planning and task boards, Tickets (added from customer support or directly from the website "clients") and more | Client Ticket System, Service Desk, Purchase Order | Notifications to technicians, GPS to detect clients, scan products (bar code) before fixing and fill the report details after fixing the problem to help other technicians.

###### The full technical details will be communicated in the next issue #3 (Définir l'environnement technique)

**Comment by ShawkiShehadeh** [comment]
![uc1 _2](https://cloud.githubusercontent.com/assets/12253555/7537332/bf46a33e-f5a0-11e4-936c-9008b776ba6e.jpg)

**Comment by ShawkiShehadeh** [comment]
![uc3_4_5](https://cloud.githubusercontent.com/assets/12253555/7537343/d202bd46-f5a0-11e4-9358-fc979f289ce6.jpg)

**Comment by ShawkiShehadeh** [comment]
![uc6_7](https://cloud.githubusercontent.com/assets/12253555/7537351/dd4d47de-f5a0-11e4-8435-65b2c76ea302.jpg)

**Comment by pascalfares** [comment]
Décision finale gestion de stock / inventsaire et trace  du patrimoine, dans un cadre "Eat de l'art" des technologie au tour de Java et l'open source
