### ISSUE TITLE
Définir l'environnement technique

### ISSUE THREAD

**Issue by pascalfares** [pascalfares/smb215-15#3]
Définir l'environnement technique

Architecture
Middlewares
Outils de developpement
Infrastructure
etc...

**Comment by Ibrahim-Keyrouz** [comment]
Plz check my updated answer :

https://github.com/pascalfares/smb215-15/issues/2

Best Regards.

Date: Tue, 5 May 2015 02:59:12 -0700

**Comment by pascalfares** [comment]
En principe

1- Technologie Java EE profil web simple avec Tomcat et/ou jetty (sans EJB)
2- Netbeans projet Maven (pour pouvoir eventueelement être interopérsble avec les developpeurs Eclispe)
3- Web services Rest

**Comment by bilani** [comment]
pouvons nous utilisons Spring MVC car elle est la nouvelle technologie?
