### ISSUE TITLE
1.1 Spécifier les fonctionalités du produit "Gestion de stock, inventaire et trace du patrimoine)

### ISSUE THREAD

**Issue by pascalfares** [pascalfares/smb215-15#7]
Spécifier les fonctionalités du produit "Gestion de stock, inventaire et trace du patrimoine)

Trouver ujn nom pour ce projet puis definir les "UC Stories"

UC Stories = Nom et description d'une fonction du système

**Comment by Ibrahim-Keyrouz** [comment]
**Parlons du Logique de L'applicatin :**
- Achat des biens d'un fournisseur pour chaque branche.
- Regler le stock de chaque branche apres achat.
- Le directeur de l'uni fait un barcode pour chaque type de produit (Chaque categorie).
- Un responsable saisi l'entree des donnees et fait la somme des totaux des categories a l'aide d'une application web; Ce total sera comparé avec celui qui se trouve sur la facture par un audit ou ... 
- Le bien sera stocké dans une branche,dans une chambre specifique.
- Le bien sera échangé entre la chambre du stockage et les autres chambres 
					et entre cette chambre et autre chambre se trouvant dans une autre branche 
					et entre cette chambre et un Employé :

a- Entre la chambre du stockage et les autres chambres d'une meme branche :
     Le responsable met les besoins de la chambre (chaise,tableau,...) , sauvgarde la relation entre le produit et la chambre , d'ou un changement du stock aura lieu.
	
	 
b- Entre la chambre du stockage et autre chambre se trouvant dans une autre branche :
	Le responsable crée le transfert OUT.
	Lorsque le responsable de l'autre branche fait le transfert IN un flag ou un simple update est fait dans la base de donnee.
	Une application mobile ou Desktop application pour localiser le chemin du camion transporteur lors du transfert de la chambre1 a chambre2 
	
c- Entre la chambre du stockage et l'Employe : 
	l'Employe , s'il a besoin, va chez la chambre du stock et a l'aide d'une application mobile qui scan le barcode puis sauvgarde la relation entre ce bien et l'Employe et puis modifie le stock 
																		ou bien a l'aide d'une application web par le saisi du responsable. 
																		
																		
- Si un produit est cassé/tombe en panne dans la nouvelle chambre ou avec un employe  , le responsable changera le status de ce produit. 

**Donc les titres generaux:** 
1- Achat
2- Stock 
3- Traçabilité
4- Rapports pour gestion 
5- cartographie 

**L'environement technique :**
1- Technologie Java EE  avec Tomcat et SSO en utilisant openID
2- Netbeans projet Maven (pour pouvoir eventueelement être interopérsble avec les developpeurs Eclispe)
3- Web services Rest pour le flag du transfert

**Comment by ShawkiShehadeh** [comment]
Description textuelle UC1

NOM : Identifier utilisateur
   
Resume :  Permet a un utilisateur de s'identifier
  
Acteurs : utilisateur 

Pre-condition :  L'utilisateur doit prealablement exister
 
Description :  
1 . Le UC commence quand l'utilisateur se connecte au SI
2 . L'utilisateur fournit l'identifiant et le mot de passe 
3 . Si l'identifiant et le mot de passe sont corrects, l'utilisateur est differencie selon sa position (Cashier, Storekeeper, Chamberlain), il est ensuite connecte au systeme et accessible aux fonctions coherentes a sa fonction
   
Exceptions :    
4 . Si les informations fournies sont incorrectes, le systeme redemande l'identifiant et le mot de passe
   
Diagramme d'activites :    

Post-condition : L'utilisateur est identifie

**Comment by ShawkiShehadeh** [comment]
Description textuelle UC2

NOM : Acheter du materiel

Resume :  Permet au caissier d'acheter du materiel d'un certain distributeur
    
Acteurs :  Caissier 

Pre-condition :  Le Caissier s'est authentifie
   
Description : 
1 . Le Caissier selectionne un distributeur, ensuite il passe a la liste des produits
2 . Il choisit les produits, a chaque choix d'un produit le prix unitaire est affiche 
3 . Il specifie la quantitee demandee de chaque produit selectionne, le prix total specifique de chaque quantitee demandee d'un certain produit est affiche
4 . A tout moment, la liste des produits selectionnes ainsi que leurs prix unitaires, quantitee demandee et prix total est affichee 
  
Exceptions :    
  
Diagramme d'activites :    
 
Post-condition : Le materiel est achete du distributeur, l'achat est detaille dans une facture

**Comment by ShawkiShehadeh** [comment]
Description textuelle UC3

NOM : Recevoir le materiel achete
   
Resume : Reception du distributeur du materiel achete par le Caissier propre a la branche en correspondence avec a la facture
    
Acteurs :  Storekeeper  

Pre-condition : Le Storekeeper s'est authentifie, l'achat du materiel par le Caissier avait deja eu lieu 
   
Description : 
1 . Le Storekeeper choisit la fonction "Reception du materiel achete", la liste des factures propres a sa branche dont le materiel correspondent n'est pas deja recus est affichee
2 . Le Sorekeeper choisit la facture concernee, la liste des produits achetes – et alors a recevoir – est affichee
3 . Le Storekeeper ratifie la reception du materiel conditionnellement a sa correspondance avec la facture; cette condition etant inexistante, le storekeeper rejetterais le materiel en s'abstenant de le recevoir  
    
Exceptions :  
   
Diagramme d'activites :    
 
Post-condition : Le materiel achete est recu et place dans la reserve sous la supervision du Storekeeper

**Comment by ShawkiShehadeh** [comment]
Description textuelle UC4

NOM : Recevoir le materiel transfere par le storekeeper d'une autre branche
   
Resume :  Reception du materiel transfere a sa propre branche par le storekeeper d'une certaine autre branche
    
Acteurs : Storekeeper  
 
Pre-condition :  Le Storekeeper s'est authentifie, le storekeeper de la branche concernee avait deja fait sa part du transfert
  
Description : 
1 . Le Storekeeper choisit la fonction "Reception du materiel transfere par une autre branche", la liste des branches est affichee
2 . Le Storekeeper choisit la branche source du materiel transfere
3 . Le Storekeeper se connecte a la BD de la branche impliquee, le materiel destine a etre transfere a sa propre branche est affiche
4 . Le Storekeeper ratifie la reception du materiel conditionnellement a sa correspondance avec la liste affichee; cette condition etant inexistante, le storekeeper rejetterais le materiel en s'abstenant de le recevoir  
    
Exceptions :    
   
Diagramme d'activites :    

Post-condition : Le materiel transfere est recu et place dans la reserve sous la supervision du Storekeeper, la branche source est informee de cet evenement

**Comment by ShawkiShehadeh** [comment]
Description textuelle UC5

NOM : Transfere du materiel a une autre branche
   
Resume : Selection d'un materiel destine a etre transfere a une certain autre branche

Acteurs : Storekeeper 

Pre-condition :  Le Storekeeper s'est authentifie, le stock contient actuellement des produits
   
Description :   
1 . Le Storekeeper choisit la fonction "Transfert de materiel vers une autre branche", la liste des branches est affichee
2 . Le storekeeper selectionne la branche destination, la liste des produits en presence dans le stock est affichee en addition de la liste des produits a transferer (initiallement vide)
3 . Le storekeeper selectionne les produits a transferer en specifiant la quantitee demandee de chaque produit, l'ajout de chaque produit est affiche dans la liste des produits a transferer
4 . Une fois termine, le Storekeeper certifie le transfert et informe la branche destination du transfert par une liste detaillee des produits transferes  
  
Exceptions : Si la quantitee a transferer d'un certain produit depasse la quantitee totale en presence dans le stock de ce produit, le systeme demande la correction de cette information   
   
Diagramme d'activites :    

Post-condition : Le materiel a transferer vers la branche est specifie, la branche destination est informee du transfert

**Comment by ShawkiShehadeh** [comment]
Description textuelle UC6

NOM : Transferer une partie du stock vers une armoire

Resume :  Selection d'une certaine partie du materiel et sa mise dans une armoire sous la supervision du Chamberlain 
    
Acteurs : Chamberlain  

Pre-condition : Le Chamberlain s'est authentifie, le stock contient actuellement des produits 

Description : 
1 . Le Chamberlain choisit la fonction "Transfert vers l'armoire", la liste des produits en presence dans le stock est affichee en addition de la liste des produits a transferer (initiallement vide)
2 . Le Chamberlain selectionne les produits a transferer en specifiant la quantitee demandee de chaque produit, l'ajout de chaque produit est affiche dans la liste des produits a transferer
3 . Une fois termine, le Chamberlain certifie le transfert  

Exceptions : Si la quantitee a transferer d'un certain produit depasse la quantitee totale en presence dans le stock de ce produit, le systeme demande la correction de cette information   

Diagramme d'activites :    

Post-condition : Le materiel a transferer vers l'armoire est specifie

**Comment by ShawkiShehadeh** [comment]
Description textuelle UC7

NOM : Distribuer les produits aux fonctionnaires de la branche

Resume : Distribution sous demande aux fonctionnaires de la branche des produits en presence dans l'armoire 
    
Acteurs :  Chamberlain  

Pre-condition : Le Chamberlain s'est authentifie, l'armoire contient actuellement des produits 

Description : 
1 . Le Chamberlain choisit la fonction "Distribution des produits", la liste des produits en presence dans l'armoire est affichee en addition de la liste des produits a distribuer (initiallement vide)  
2 . Le Chamberlain selectionne les produits a transferer en specifiant la quantitee demandee de chaque produit, l'ajout de chaque produit est affiche dans la liste des produits a distribuer
3 . Une fois termine, le Chamberlain certifie la distribution
  
Exceptions : Si la quantitee a distribuer d'un certain produit depasse la quantitee totale en presence dans l'armoire de ce produit, le systeme demande la correction de cette information      

Diagramme d'activites :    

Post-condition : Le materiel a distribuer est specifie

**Comment by ShawkiShehadeh** [comment]
![uc1](https://cloud.githubusercontent.com/assets/12253555/7788882/af8969ec-0255-11e5-97a4-f063c564247c.jpg)

**Comment by ShawkiShehadeh** [comment]
![uc2](https://cloud.githubusercontent.com/assets/12253555/7788887/ce575280-0255-11e5-9e8d-93c03c256309.jpg)

**Comment by ShawkiShehadeh** [comment]
![uc3](https://cloud.githubusercontent.com/assets/12253555/7788892/d5761970-0255-11e5-825c-c59fb4aebc85.jpg)

**Comment by ShawkiShehadeh** [comment]
![uc4](https://cloud.githubusercontent.com/assets/12253555/7788893/dbe85818-0255-11e5-94fa-c58c0759996b.jpg)

**Comment by ShawkiShehadeh** [comment]
![uc5](https://cloud.githubusercontent.com/assets/12253555/7788894/e0c20ab4-0255-11e5-96b9-8da04db925d0.jpg)

**Comment by ShawkiShehadeh** [comment]
![uc6](https://cloud.githubusercontent.com/assets/12253555/7788895/e553d85a-0255-11e5-8faa-60f81e5d9b78.jpg)

**Comment by ShawkiShehadeh** [comment]
![uc7](https://cloud.githubusercontent.com/assets/12253555/7788896/e9c7d670-0255-11e5-9038-e9a01ac6d503.jpg)

**Comment by pascalfares** [comment]
Mettre ceci dans un document dans un de vos projets git
